name: Daily Updater

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      id: checkout-code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: echo "Install Dependencies"
    
    - name: Setup jq
      uses: dcarbone/install-jq-action@v1.0.1
    
    - name: Run Script
      env:
        TRACKMANIA_API_USERNAME: ${{ secrets.TRACKMANIA_API_USERNAME }}
        TRACKMANIA_API_PASSWORD: ${{ secrets.TRACKMANIA_API_PASSWORD }}
      run: |
        ./update.sh 5 387678 'MONTHLY TOP TRACKS' \
        && ./update.sh 4 391695 'WEEKLY TOP TRACKS'